#!/usr/bin/env python3
"""Regression tests for V3 FS2 release packaging, using real mkspiffs mounts.

Pass a firmware directory to exercise a compiled release pair. With no argument
only a clearly synthetic ESP container is used; it is never a flashable artifact.
Temporary fixtures never overwrite the supplied firmware files.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import struct
import tempfile
from unittest.mock import patch

from validate_release_v3 import (
    PAIR, PARTITION_OFFSET, PARTITION_SECTOR, PAGE_SIZE, BLOCK_SIZE,
    find_mkspiffs, run_tool, parse_partitions, inspect_fresh_spiffs,
    validate_v3_pair, factory_spiffs_sha256,
)


def table_bytes(entries: list[tuple]) -> bytes:
    rows = b"".join(struct.pack("<HBBII16sI", 0x50AA, *entry) for entry in entries)
    rows += b"\xeb\xeb" + b"\xff" * 14 + hashlib.md5(rows).digest()
    return rows.ljust(PARTITION_SECTOR, b"\xff")


def table_changed(merged: bytes, change) -> bytes:
    entries = [[entry["type"], entry["subtype"], entry["offset"], entry["size"],
                entry["name"].encode(), entry["flags"]] for entry in parse_partitions(merged)]
    change(entries)
    mutated = bytearray(merged)
    mutated[PARTITION_OFFSET:PARTITION_OFFSET + PARTITION_SECTOR] = table_bytes(entries)
    return bytes(mutated)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("firmware_dir", nargs="?", type=Path)
    args = parser.parse_args()
    tool = find_mkspiffs()
    passed = 0
    with tempfile.TemporaryDirectory(prefix="smartui-v3-fs1-regression-") as folder:
        temp = Path(folder)
        empty = temp / "empty"
        empty.mkdir()
        def formatted(name, size, page=PAGE_SIZE, block=BLOCK_SIZE, content=empty):
            image = temp / f"{name}.bin"
            run_tool(tool, "-c", content, "-s", size, "-p", page, "-b", block, image)
            return image.read_bytes()
        if args.firmware_dir:
            validate_v3_pair(args.firmware_dir)
            merged = (args.firmware_dir / f"{PAIR.stem}-freshInstall-merged.bin").read_bytes()
            update = (args.firmware_dir / f"{PAIR.stem}-update.bin").read_bytes()
            scope = "actual supplied compiled release pair"
        else:
            # Synthetic packaging fixture only: not a real application or bootloader.
            payload = PAIR.marker + b"\0" + factory_spiffs_sha256().encode("ascii") + b"\0" * 32
            update = b"\xe9\x01\x00\x30" + b"\0" * 20 + struct.pack("<II", 0x3C000020, len(payload)) + payload
            checksum = 0xEF
            for value in payload: checksum ^= value
            update += b"\0" * (((len(update) + 16) & ~15) - len(update) - 1) + bytes([checksum])
            entries = [(1, 2, 0x9000, 0x5000, b"nvs", 0),
                       (1, 0, 0xE000, 0x2000, b"otadata", 0),
                       (0, 0x10, 0x10000, 0x330000, b"app0", 0),
                       (0, 0x11, 0x340000, 0x330000, b"app1", 0),
                       (1, 0x82, 0x670000, 0x180000, b"spiffs", 0),
                       (1, 3, 0x7F0000, 0x10000, b"coredump", 0)]
            merged = bytearray(b"\xff" * 0x7F0000)
            merged[:24] = update[:24]
            merged[PARTITION_OFFSET:PARTITION_OFFSET + PARTITION_SECTOR] = table_bytes(entries)
            merged[0x10000:0x10000 + len(update)] = update
            merged[0x670000:0x7F0000] = formatted("valid", 0x180000)
            merged = bytes(merged)
            scope = "synthetic ESP container; SPIFFS itself generated by real pinned mkspiffs"
        metadata = inspect_fresh_spiffs(merged)
        offset, size = metadata["offset"], metadata["size"]
        original = merged[offset:offset + size]
        def with_fs(fs):
            assert len(fs) == size
            return merged[:offset] + fs + merged[offset + size:]
        def accepted(label, action):
            nonlocal passed
            action()
            passed += 1
            print(f"[PASS] {label}")
        def rejected(label, action, expected):
            nonlocal passed
            try:
                action()
            except ValueError as error:
                if expected not in str(error):
                    raise AssertionError(f"{label}: wrong rejection: {error}") from error
            else:
                raise AssertionError(f"{label}: invalid image was accepted")
            passed += 1
            print(f"[PASS] rejects {label}")
        accepted("complete formatted empty SPIFFS mounts", lambda: inspect_fresh_spiffs(merged))
        with patch("validate_release_v3.factory_spiffs_sha256", return_value="0" * 64):
            rejected("image hash differs from runtime recovery guard", lambda: inspect_fresh_spiffs(merged), "differs from V3StorageRecovery.h")
        rejected("old merged without FS", lambda: inspect_fresh_spiffs(merged[:0x10000 + len(update)]), "missing the complete")
        rejected("truncated FS", lambda: inspect_fresh_spiffs(merged[:offset + size - 1]), "missing the complete")
        rejected("erased FF partition", lambda: inspect_fresh_spiffs(with_fs(b"\xff" * size)), "erased")
        rejected("corrupt FS", lambda: inspect_fresh_spiffs(with_fs(b"\0" * size)), "mkspiffs failed")
        rejected("wrong page geometry", lambda: inspect_fresh_spiffs(with_fs(formatted("page512", size, page=512))), "mkspiffs failed")
        rejected("wrong block geometry", lambda: inspect_fresh_spiffs(with_fs(formatted("block8192", size, block=8192))), "mkspiffs failed")
        populated = temp / "populated"
        populated.mkdir()
        (populated / "identity-fixture").write_bytes(b"NOT A REAL IDENTITY; TEST ONLY")
        rejected("nonempty user-data filesystem", lambda: inspect_fresh_spiffs(with_fs(formatted("populated", size, content=populated))), "contains files")
        stale = bytearray(original)
        # An unused data page can carry stale bytes without appearing in readdir.
        stale[1024] = 0x42
        rejected("hidden stale bytes despite empty listing", lambda: inspect_fresh_spiffs(with_fs(bytes(stale))), "pristine canonical")
        damaged_table = bytearray(merged)
        damaged_table[PARTITION_OFFSET + 12] ^= 1
        rejected("partition MD5 mismatch", lambda: inspect_fresh_spiffs(bytes(damaged_table)), "MD5 mismatch")
        overlapping = table_changed(merged, lambda entries: entries[4].__setitem__(2, 0x10000))
        rejected("overlapping partitions with valid MD5", lambda: inspect_fresh_spiffs(overlapping), "overlapping")
        duplicate = table_changed(merged, lambda entries: entries[5].__setitem__(1, 0x82))
        rejected("ambiguous two SPIFFS partitions", lambda: inspect_fresh_spiffs(duplicate), "exactly one")
        encrypted = table_changed(merged, lambda entries: entries[4].__setitem__(5, 1))
        rejected("unsupported encrypted SPIFFS", lambda: inspect_fresh_spiffs(encrypted), "unencrypted")
        fixture = temp / "pair"
        fixture.mkdir()
        (fixture / f"{PAIR.stem}-freshInstall-merged.bin").write_bytes(merged)
        update_path = fixture / f"{PAIR.stem}-update.bin"
        update_path.write_bytes(update)
        accepted("exact update/application bytes and FS2 marker", lambda: validate_v3_pair(fixture))
        changed = bytearray(update)
        changed[-1] ^= 1
        update_path.write_bytes(changed)
        rejected("update differs from merged application", lambda: validate_v3_pair(fixture), "slice differs")
        update_path.write_bytes(update + b"\xff" * size)
        rejected("FF padding appended to update payload", lambda: validate_v3_pair(fixture), "trailing bytes")
        update_path.write_bytes(update + original)
        rejected("filesystem appended to update payload", lambda: validate_v3_pair(fixture), "slice differs")
    print(f"V3 FS2 storage regression: {passed} passed; {scope}.")
    print("Host mount/configuration tests only; not an ESP32 boot or hardware test.")


if __name__ == "__main__":
    main()
